import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  detail,
  team,
  user,
}: {
  children: React.ReactNode;
  detail: React.ReactNode;
  team: React.ReactNode;
  user: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} w-screen h-screen flex justify-center`}
      >
        <div className="w-full max-w-4xl flex justify-between p-5">
          {user}
          {team}
          {detail}
        </div>
      </body>
    </html>
  );
}
